# -------------------------------------------------------------
# CONFIGURACIÓN GENERAL DEL SITIO
# -------------------------------------------------------------
site_name: PPS-Unidad1-Tarea-PPS  # Define el título que aparecerá en la barra de navegación y en la etiqueta <title> del navegador.
site_description: Actividad Unidad 1 - Prueba de Aplicaciones

# -------------------------------------------------------------
# ESTRUCTURA DE NAVEGACIÓN (MENÚ)
# -------------------------------------------------------------
# Define la lista de enlaces y el orden de aparición en el menú de navegación principal.
nav:
  # El nombre de la sección en el menú: nombre_archivo.md
  - Home: index.md             # Primer elemento del menú, enlaza con el archivo 'index.md'.
  # Se pueden añadir subsecciones anidando listas:
  # - Referencia: 
  #   - Funciones: referencia/funciones.md
  #   - Clases: referencia/clases.md

# -------------------------------------------------------------
# DIRECTORIOS
# -------------------------------------------------------------
# Ruta de la carpeta que contiene todos los archivos .md (Markdown) de la documentación.
# MkDocs buscará aquí los archivos listados en 'nav'.
doc_dir: docs 
# -------------------------------------------------------------
# TEMA (Opcional, pero común)
# -------------------------------------------------------------
# theme: 
#   name: 'material' # Si usas el popular tema Material for MkDocs.
#   # highlightjs: true
#   # code_fences: true
